In [32]:
import pandas as pd

In [33]:
truedata = pd.read_csv('/home/briskk/Datasets/Compare/tcpdump.list', sep = ' ',header=None)

In [34]:
truedata1 = truedata.iloc[:,6:11]
truedata1.head()

     6   7                8                9   10
0  1024  25  172.016.113.084  135.013.216.191   0
1    53  53  192.168.001.010  172.016.112.020   0
2    53  53  192.168.001.010  172.016.112.020   0
3  1025  25  172.016.113.084  197.182.091.233   0
4    53  53  172.016.112.020  192.168.001.020   0

In [35]:
truedata1.to_csv('/home/briskk/Datasets/Compare/truelist.csv',index=0,header=0)

In [36]:
truelist = pd.read_csv('/home/briskk/Datasets/Compare/truelist.csv', names=['src_port', 'dst_port', 'src_ip', 'dst_ip', 'type'])
truelist.head()

  src_port dst_port           src_ip           dst_ip  type
0     1024       25  172.016.113.084  135.013.216.191     0
1       53       53  192.168.001.010  172.016.112.020     0
2       53       53  192.168.001.010  172.016.112.020     0
3     1025       25  172.016.113.084  197.182.091.233     0
4       53       53  172.016.112.020  192.168.001.020     0

In [37]:
predictlist = pd.read_csv('/home/briskk/Datasets/Compare/hyp.csv',sep = ' ', names = ['time','src_port', 'dst_port', 'src_ip', 'dst_ip', 'type'] )
predictlist.head()
df_time = predictlist.time
predictlist = predictlist.drop('time', axis=1)
predictlist

        src_port  dst_port          src_ip           dst_ip  type
0           1024        25   172.16.113.84   135.13.216.191     0
1           1025        25   172.16.113.84   197.182.91.233     0
2           1026        80  172.16.112.207    206.79.171.54     0
3           1027        80  172.16.112.207     207.77.90.16     0
4           1024        79  197.218.177.69   172.16.113.204     0
5           1026        25  197.218.177.69   172.16.113.204     0
6           1028        80  172.16.115.234     209.1.224.15     0
7           1029        80  172.16.115.234     209.1.224.15     0
8           1048        80  172.16.115.234     209.1.224.15     0
9           1049        80  172.16.115.234     209.1.224.15     0
10          1051        80  172.16.115.234     209.1.224.15     0
11          1052        80  172.16.115.234     209.1.224.15     0
12          1104        80  172.16.115.234     209.1.224.15     0
13          1106        80  172.16.115.234     209.1.224.15     0
14          1107        80  172.16.115.234     209.1.224.15     0
15          1108        80  172.16.115.234     209.1.224.15     0
16          1109        80  172.16.115.234     209.1.224.15     0
17          1111        80  172.16.115.234     209.1.224.15     0
18          1112        80  172.16.115.234     209.1.224.15     0
19          1113        80  172.16.115.234     209.1.224.15     0
20          1115        80  172.16.115.234     209.1.224.15     0
21            20      1028  172.16.114.148   197.218.177.69     0
22            20      1049  172.16.114.148   197.218.177.69     0
23            20      1052  172.16.114.148   197.218.177.69     0
24            20      1104  172.16.114.148   197.218.177.69     0
25            20      1106  172.16.114.148   197.218.177.69     0
26            20      1107  172.16.114.148   197.218.177.69     0
27          1169        80  172.16.115.234     209.1.224.15     0
28          1116        80  172.16.115.234   207.211.106.40     0
29          1170        80  172.16.115.234     209.1.224.15     0
...          ...       ...             ...              ...   ...
222858     33051        23         9.9.9.9    172.16.112.50     1
222859     33307        20         9.9.9.9    172.16.112.50     1
222860     33051        79         9.9.9.9    172.16.112.50     1
222861     33307        23         9.9.9.9    172.16.112.50     1
222862     33563        20         9.9.9.9    172.16.112.50     1
222863     33307        79         9.9.9.9    172.16.112.50     1
222864     33563        23         9.9.9.9    172.16.112.50     1
222865     33819        20         9.9.9.9    172.16.112.50     1
222866     33563        79         9.9.9.9    172.16.112.50     1
222867     33819        23         9.9.9.9    172.16.112.50     1
222868     34075        20         9.9.9.9    172.16.112.50     1
222869      1674       161   194.27.251.21      192.168.1.1     0
222870      7616        80  172.16.115.234  208.228.229.225     0
222871      1676       161   194.27.251.21      192.168.1.1     0
222872      1679       161   194.27.251.21      192.168.1.1     0
222873      7617        80  172.16.115.234     198.3.98.160     0
222874      7615        21  172.16.114.168   197.218.177.69     0
222875      1681       161   194.27.251.21      192.168.1.1     0
222876     26644        25   196.37.75.158   172.16.114.169     0
222877      1686       161   194.27.251.21      192.168.1.1     0
222878      1694       161   194.27.251.21      192.168.1.1     0
222879       161      1688     192.168.1.1    194.27.251.21     1
222880         0         0     192.168.1.1      192.168.1.5     1
222881        20     26652  172.16.114.148   196.227.33.189     0
222882      1849        53  172.16.117.103     192.168.1.10     0
222883         0         0    192.168.1.90     192.168.1.10     1
222884     26689        25   194.7.248.153   172.16.114.168     0
222885      7618        80  172.16.112.207   204.71.177.179     0
222886      7808        80  172.16.113.105  136.149.142.178     0
222887      1767       161   194.27.251.21      192.168.1.1     0

[222888 rows x 5 columns]

In [59]:
predictlist['src_port'].value_counts()

0        7767
49724    1015
20        872
2604      478
23        303
1234      166
25        142
161        68
53         65
123        32
7180       32
24709      25
6831       21
6251       20
79         20
2741       20
1695       19
1693       18
1691       17
1184       17
1163       16
1168       16
1170       16
1686       16
1681       16
1169       16
1166       16
1904       16
4194       16
1700       16
         ...
63831       1
33368       1
64087       1
12878       1
8780        1
21058       1
16960       1
2505        1
22979       1
37210       1
35161       1
2838        1
29465       1
33112       1
12622       1
61274       1
32984       1
12494       1
6347        1
36954       1
34905       1
32856       1
63575       1
11          1
4105        1
72          1
24644       1
20546       1
16448       1
35671       1
Name: src_port, Length: 28962, dtype: int64

In [58]:
truelist['src_port'].value_counts()

-        9875
161      2542
49724    1015
20        835
1000      772
1234      167
53         65
123        41
1184       22
1695       21
1176       19
1174       19
1691       18
1170       18
1163       18
1135       18
1166       18
1703       18
1206       17
1700       17
1693       17
1167       17
1192       16
1190       16
1146       16
1665       16
1168       16
1923       16
1681       16
1685       16
         ...
63322       1
4604        1
26455       1
50266       1
32808       1
14924       1
30751       1
17609       1
31832       1
28721       1
31064       1
28961       1
21000       1
6184        1
20413       1
53080       1
10304       1
4678        1
9404        1
24810       1
63577       1
1258        1
6745        1
41149       1
31834       1
27223       1
8165        1
7514        1
22874       1
20229       1
Name: src_port, Length: 28862, dtype: int64

In [16]:
truelist.shape

(227166, 5)

In [17]:
predictlist.shape

(222888, 5)

In [38]:
truelist['src_ip']

0         172.016.113.084
1         192.168.001.010
2         192.168.001.010
3         172.016.113.084
4         172.016.112.020
5         172.016.112.020
6         172.016.112.207
7         172.016.112.207
8         197.218.177.069
9         172.016.115.234
10        197.218.177.069
11        197.218.177.069
12        172.016.115.234
13        172.016.115.234
14        172.016.115.234
15        172.016.115.234
16        172.016.115.234
17        172.016.115.234
18        172.016.115.234
19        172.016.115.234
20        172.016.115.234
21        172.016.115.234
22        172.016.115.234
23        172.016.115.234
24        172.016.115.234
25        172.016.115.234
26        172.016.115.234
27        172.016.114.148
28        172.016.114.148
29        194.027.251.021
               ...
227136    192.168.001.001
227137    196.227.033.189
227138    172.016.115.005
227139    192.168.001.090
227140    172.016.117.103
227141    194.027.251.021
227142    192.168.001.001
227143    194.007.248.153
227144    196.227.033.189
227145    192.168.001.001
227146    194.027.251.021
227147    194.027.251.021
227148    194.027.251.021
227149    194.027.251.021
227150    194.027.251.021
227151    194.027.251.021
227152    194.027.251.021
227153    196.227.033.189
227154    172.016.112.207
227155    172.016.113.105
227156    192.168.001.001
227157    194.027.251.021
227158    192.168.001.001
227159    192.168.001.001
227160    192.168.001.001
227161    192.168.001.001
227162    192.168.001.001
227163    194.027.251.021
227164    194.027.251.021
227165    192.168.001.001
Name: src_ip, Length: 227166, dtype: object

## 将官方list中的ip地址中的多余的0去掉，转换成标准ip地址

In [39]:
true_srcip = []
for i in truelist['src_ip']:
    trasformedsrc = ".".join([str(int(s)) for s in i.split(".")])
    true_srcip.append(trasformedsrc)
true_dstip = []
for i in truelist['dst_ip']:
    transformeddst = '.'.join([str(int(s)) for s in i.split(".")])
    true_dstip.append(transformeddst)

In [40]:
true_src_ip = pd.DataFrame(true_srcip)
true_src_ip.columns = ['src_ip']
true_dst_ip = pd.DataFrame(true_dstip)
true_dst_ip.columns = ['dst_ip']

In [41]:
print(true_src_ip.shape,true_dst_ip.shape)

(227166, 1) (227166, 1)

## 将src_ip,dst_ip插入到truelist正确位置上

In [77]:
truelist_1 = truelist.drop(['src_ip', 'dst_ip'], axis=1, inplace=False)

In [78]:
truelist_1 = pd.concat([truelist_1, true_src_ip, true_dst_ip], axis=1)

In [79]:
truelist_1.shape

(227166, 5)

In [80]:
df_src = truelist_1.src_ip
truelist_1 = truelist_1.drop('src_ip', axis=1)
truelist_1.insert(2, 'src_ip', df_src)

In [81]:
df_dst = truelist_1.dst_ip
truelist_1 = truelist_1.drop('dst_ip', axis=1)
truelist_1.insert(3, 'dst_ip', df_dst)

## 首先合并两个dataframe，然后去除重复的

In [62]:
import numpy as np

In [65]:
truelist_1['src_port'].astype(np.int64)

ValueError: invalid literal for int() with base 10: '-'

In [66]:
truelist_1

       src_port dst_port          src_ip           dst_ip  type
0          1024       25   172.16.113.84   135.13.216.191     0
1            53       53    192.168.1.10    172.16.112.20     0
2            53       53    192.168.1.10    172.16.112.20     0
3          1025       25   172.16.113.84   197.182.91.233     0
4            53       53   172.16.112.20     192.168.1.20     0
5            53       53   172.16.112.20     192.168.1.20     0
6          1026       80  172.16.112.207    206.79.171.54     0
7          1027       80  172.16.112.207     207.77.90.16     0
8          1024       79  197.218.177.69   172.16.113.204     0
9          1028       80  172.16.115.234     209.1.224.15     0
10         1026       25  197.218.177.69   172.16.113.204     0
11         1027       21  197.218.177.69   172.16.114.148     0
12         1029       80  172.16.115.234     209.1.224.15     0
13         1048       80  172.16.115.234     209.1.224.15     0
14         1049       80  172.16.115.234     209.1.224.15     0
15         1051       80  172.16.115.234     209.1.224.15     0
16         1052       80  172.16.115.234     209.1.224.15     0
17         1104       80  172.16.115.234     209.1.224.15     0
18         1106       80  172.16.115.234     209.1.224.15     0
19         1107       80  172.16.115.234     209.1.224.15     0
20         1108       80  172.16.115.234     209.1.224.15     0
21         1109       80  172.16.115.234     209.1.224.15     0
22         1111       80  172.16.115.234     209.1.224.15     0
23         1112       80  172.16.115.234     209.1.224.15     0
24         1113       80  172.16.115.234     209.1.224.15     0
25         1115       80  172.16.115.234     209.1.224.15     0
26         1116       80  172.16.115.234   207.211.106.40     0
27           20     1028  172.16.114.148   197.218.177.69     0
28           20     1049  172.16.114.148   197.218.177.69     0
29         1060      161   194.27.251.21      192.168.1.1     0
...         ...      ...             ...              ...   ...
222858    33051       23         9.9.9.9    172.16.112.50     1
222859    33307       20         9.9.9.9    172.16.112.50     1
222860    33051       79         9.9.9.9    172.16.112.50     1
222861    33307       23         9.9.9.9    172.16.112.50     1
222862    33563       20         9.9.9.9    172.16.112.50     1
222863    33307       79         9.9.9.9    172.16.112.50     1
222864    33563       23         9.9.9.9    172.16.112.50     1
222865    33819       20         9.9.9.9    172.16.112.50     1
222866    33563       79         9.9.9.9    172.16.112.50     1
222867    33819       23         9.9.9.9    172.16.112.50     1
222868    34075       20         9.9.9.9    172.16.112.50     1
222869     1674      161   194.27.251.21      192.168.1.1     0
222870     7616       80  172.16.115.234  208.228.229.225     0
222871     1676      161   194.27.251.21      192.168.1.1     0
222872     1679      161   194.27.251.21      192.168.1.1     0
222873     7617       80  172.16.115.234     198.3.98.160     0
222874     7615       21  172.16.114.168   197.218.177.69     0
222875     1681      161   194.27.251.21      192.168.1.1     0
222876    26644       25   196.37.75.158   172.16.114.169     0
222877     1686      161   194.27.251.21      192.168.1.1     0
222878     1694      161   194.27.251.21      192.168.1.1     0
222879      161     1688     192.168.1.1    194.27.251.21     1
222880        0        0     192.168.1.1      192.168.1.5     1
222881       20    26652  172.16.114.148   196.227.33.189     0
222882     1849       53  172.16.117.103     192.168.1.10     0
222883        0        0    192.168.1.90     192.168.1.10     1
222884    26689       25   194.7.248.153   172.16.114.168     0
222885     7618       80  172.16.112.207   204.71.177.179     0
222886     7808       80  172.16.113.105  136.149.142.178     0
222887     1767      161   194.27.251.21      192.168.1.1     0

[450054 rows x 5 columns]

In [67]:
predictlist

        src_port  dst_port          src_ip           dst_ip  type
0           1024        25   172.16.113.84   135.13.216.191     0
1           1025        25   172.16.113.84   197.182.91.233     0
2           1026        80  172.16.112.207    206.79.171.54     0
3           1027        80  172.16.112.207     207.77.90.16     0
4           1024        79  197.218.177.69   172.16.113.204     0
5           1026        25  197.218.177.69   172.16.113.204     0
6           1028        80  172.16.115.234     209.1.224.15     0
7           1029        80  172.16.115.234     209.1.224.15     0
8           1048        80  172.16.115.234     209.1.224.15     0
9           1049        80  172.16.115.234     209.1.224.15     0
10          1051        80  172.16.115.234     209.1.224.15     0
11          1052        80  172.16.115.234     209.1.224.15     0
12          1104        80  172.16.115.234     209.1.224.15     0
13          1106        80  172.16.115.234     209.1.224.15     0
14          1107        80  172.16.115.234     209.1.224.15     0
15          1108        80  172.16.115.234     209.1.224.15     0
16          1109        80  172.16.115.234     209.1.224.15     0
17          1111        80  172.16.115.234     209.1.224.15     0
18          1112        80  172.16.115.234     209.1.224.15     0
19          1113        80  172.16.115.234     209.1.224.15     0
20          1115        80  172.16.115.234     209.1.224.15     0
21            20      1028  172.16.114.148   197.218.177.69     0
22            20      1049  172.16.114.148   197.218.177.69     0
23            20      1052  172.16.114.148   197.218.177.69     0
24            20      1104  172.16.114.148   197.218.177.69     0
25            20      1106  172.16.114.148   197.218.177.69     0
26            20      1107  172.16.114.148   197.218.177.69     0
27          1169        80  172.16.115.234     209.1.224.15     0
28          1116        80  172.16.115.234   207.211.106.40     0
29          1170        80  172.16.115.234     209.1.224.15     0
...          ...       ...             ...              ...   ...
222858     33051        23         9.9.9.9    172.16.112.50     1
222859     33307        20         9.9.9.9    172.16.112.50     1
222860     33051        79         9.9.9.9    172.16.112.50     1
222861     33307        23         9.9.9.9    172.16.112.50     1
222862     33563        20         9.9.9.9    172.16.112.50     1
222863     33307        79         9.9.9.9    172.16.112.50     1
222864     33563        23         9.9.9.9    172.16.112.50     1
222865     33819        20         9.9.9.9    172.16.112.50     1
222866     33563        79         9.9.9.9    172.16.112.50     1
222867     33819        23         9.9.9.9    172.16.112.50     1
222868     34075        20         9.9.9.9    172.16.112.50     1
222869      1674       161   194.27.251.21      192.168.1.1     0
222870      7616        80  172.16.115.234  208.228.229.225     0
222871      1676       161   194.27.251.21      192.168.1.1     0
222872      1679       161   194.27.251.21      192.168.1.1     0
222873      7617        80  172.16.115.234     198.3.98.160     0
222874      7615        21  172.16.114.168   197.218.177.69     0
222875      1681       161   194.27.251.21      192.168.1.1     0
222876     26644        25   196.37.75.158   172.16.114.169     0
222877      1686       161   194.27.251.21      192.168.1.1     0
222878      1694       161   194.27.251.21      192.168.1.1     0
222879       161      1688     192.168.1.1    194.27.251.21     1
222880         0         0     192.168.1.1      192.168.1.5     1
222881        20     26652  172.16.114.148   196.227.33.189     0
222882      1849        53  172.16.117.103     192.168.1.10     0
222883         0         0    192.168.1.90     192.168.1.10     1
222884     26689        25   194.7.248.153   172.16.114.168     0
222885      7618        80  172.16.112.207   204.71.177.179     0
222886      7808        80  172.16.113.105  136.149.142.178     0
222887      1767       161   194.27.251.21      192.168.1.1     0

[222888 rows x 5 columns]

In [47]:
truelist_1 = truelist_1.append(predictlist)

In [69]:
truelist_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 450054 entries, 0 to 222887
Data columns (total 5 columns):
src_port    450054 non-null object
dst_port    450054 non-null object
src_ip      450054 non-null object
dst_ip      450054 non-null object
type        450054 non-null int64
dtypes: int64(1), object(4)
memory usage: 20.6+ MB

In [72]:
truelist_1.sort_values('src_ip')

       src_port dst_port   src_ip         dst_ip  type
21994      1000       23  1.1.1.1  172.16.112.50     1
21886      1000       23  1.1.1.1  172.16.112.50     1
21885      1000       23  1.1.1.1  172.16.112.50     1
21847      1000       23  1.1.1.1  172.16.112.50     1
21835      1000       23  1.1.1.1  172.16.112.50     1
21834      1000       23  1.1.1.1  172.16.112.50     1
21833      1000       23  1.1.1.1  172.16.112.50     1
21832      1000       23  1.1.1.1  172.16.112.50     1
21831      1000       23  1.1.1.1  172.16.112.50     1
21830      1000       23  1.1.1.1  172.16.112.50     1
21829      1000       23  1.1.1.1  172.16.112.50     1
21828      1000       23  1.1.1.1  172.16.112.50     1
21888      1000       23  1.1.1.1  172.16.112.50     1
21827      1000       23  1.1.1.1  172.16.112.50     1
21825      1000       23  1.1.1.1  172.16.112.50     1
21824      1000       23  1.1.1.1  172.16.112.50     1
21823      1000       23  1.1.1.1  172.16.112.50     1
21822      1000       23  1.1.1.1  172.16.112.50     1
21821      1000       23  1.1.1.1  172.16.112.50     1
21820      1000       23  1.1.1.1  172.16.112.50     1
21819      1000       23  1.1.1.1  172.16.112.50     1
21818      1000       23  1.1.1.1  172.16.112.50     1
21816      1000       23  1.1.1.1  172.16.112.50     1
21815      1000       23  1.1.1.1  172.16.112.50     1
21814      1000       23  1.1.1.1  172.16.112.50     1
21826      1000       23  1.1.1.1  172.16.112.50     1
21813      1000       23  1.1.1.1  172.16.112.50     1
21889      1000       23  1.1.1.1  172.16.112.50     1
21891      1000       23  1.1.1.1  172.16.112.50     1
22073      1000       23  1.1.1.1  172.16.112.50     1
...         ...      ...      ...            ...   ...
227096    28187       80  9.9.9.9  172.16.112.50     1
227095    30491       79  9.9.9.9  172.16.112.50     1
227094    32027       79  9.9.9.9  172.16.112.50     1
213844     5132       20  9.9.9.9  172.16.112.50     1
213818     3084       80  9.9.9.9  172.16.112.50     1
213843     4876       23  9.9.9.9  172.16.112.50     1
213841     4620       23  9.9.9.9  172.16.112.50     1
213820     3340       20  9.9.9.9  172.16.112.50     1
213821     3340       80  9.9.9.9  172.16.112.50     1
213822     3340       79  9.9.9.9  172.16.112.50     1
213823     3340       23  9.9.9.9  172.16.112.50     1
213824     3596       20  9.9.9.9  172.16.112.50     1
213825     3596       79  9.9.9.9  172.16.112.50     1
213826     3596       80  9.9.9.9  172.16.112.50     1
213827     3596       23  9.9.9.9  172.16.112.50     1
213828     3852       20  9.9.9.9  172.16.112.50     1
213829     3852       80  9.9.9.9  172.16.112.50     1
213830     3852       79  9.9.9.9  172.16.112.50     1
213831     3852       23  9.9.9.9  172.16.112.50     1
213832     4108       20  9.9.9.9  172.16.112.50     1
213833     4108       79  9.9.9.9  172.16.112.50     1
213834     4108       80  9.9.9.9  172.16.112.50     1
213835     4364       79  9.9.9.9  172.16.112.50     1
213836     4108       23  9.9.9.9  172.16.112.50     1
213837     4364       20  9.9.9.9  172.16.112.50     1
213838     4620       79  9.9.9.9  172.16.112.50     1
213839     4364       23  9.9.9.9  172.16.112.50     1
213840     4620       20  9.9.9.9  172.16.112.50     1
213842     4876       20  9.9.9.9  172.16.112.50     1
226153     3604       20  9.9.9.9  172.16.112.50     1

[450054 rows x 5 columns]

In [48]:
result = truelist_1.drop_duplicates(keep=False)

In [49]:
result

       src_port dst_port          src_ip           dst_ip  type
0          1024       25   172.16.113.84   135.13.216.191     0
3          1025       25   172.16.113.84   197.182.91.233     0
6          1026       80  172.16.112.207    206.79.171.54     0
7          1027       80  172.16.112.207     207.77.90.16     0
8          1024       79  197.218.177.69   172.16.113.204     0
9          1028       80  172.16.115.234     209.1.224.15     0
10         1026       25  197.218.177.69   172.16.113.204     0
11         1027       21  197.218.177.69   172.16.114.148     0
12         1029       80  172.16.115.234     209.1.224.15     0
13         1048       80  172.16.115.234     209.1.224.15     0
14         1049       80  172.16.115.234     209.1.224.15     0
15         1051       80  172.16.115.234     209.1.224.15     0
16         1052       80  172.16.115.234     209.1.224.15     0
17         1104       80  172.16.115.234     209.1.224.15     0
18         1106       80  172.16.115.234     209.1.224.15     0
19         1107       80  172.16.115.234     209.1.224.15     0
20         1108       80  172.16.115.234     209.1.224.15     0
21         1109       80  172.16.115.234     209.1.224.15     0
22         1111       80  172.16.115.234     209.1.224.15     0
23         1112       80  172.16.115.234     209.1.224.15     0
24         1113       80  172.16.115.234     209.1.224.15     0
25         1115       80  172.16.115.234     209.1.224.15     0
26         1116       80  172.16.115.234   207.211.106.40     0
27           20     1028  172.16.114.148   197.218.177.69     0
28           20     1049  172.16.114.148   197.218.177.69     0
29         1060      161   194.27.251.21      192.168.1.1     0
30          161     1060     192.168.1.1    194.27.251.21     0
31           20     1052  172.16.114.148   197.218.177.69     0
32           20     1104  172.16.114.148   197.218.177.69     0
33         1063      161   194.27.251.21      192.168.1.1     0
...         ...      ...             ...              ...   ...
222851    32539       23         9.9.9.9    172.16.112.50     1
222852    32795       20         9.9.9.9    172.16.112.50     1
222853    32795       80         9.9.9.9    172.16.112.50     1
222854    32539       79         9.9.9.9    172.16.112.50     1
222855    32795       23         9.9.9.9    172.16.112.50     1
222856    33051       20         9.9.9.9    172.16.112.50     1
222857    32795       79         9.9.9.9    172.16.112.50     1
222858    33051       23         9.9.9.9    172.16.112.50     1
222859    33307       20         9.9.9.9    172.16.112.50     1
222860    33051       79         9.9.9.9    172.16.112.50     1
222861    33307       23         9.9.9.9    172.16.112.50     1
222862    33563       20         9.9.9.9    172.16.112.50     1
222863    33307       79         9.9.9.9    172.16.112.50     1
222864    33563       23         9.9.9.9    172.16.112.50     1
222865    33819       20         9.9.9.9    172.16.112.50     1
222866    33563       79         9.9.9.9    172.16.112.50     1
222867    33819       23         9.9.9.9    172.16.112.50     1
222868    34075       20         9.9.9.9    172.16.112.50     1
222870     7616       80  172.16.115.234  208.228.229.225     0
222873     7617       80  172.16.115.234     198.3.98.160     0
222874     7615       21  172.16.114.168   197.218.177.69     0
222876    26644       25   196.37.75.158   172.16.114.169     0
222879      161     1688     192.168.1.1    194.27.251.21     1
222880        0        0     192.168.1.1      192.168.1.5     1
222881       20    26652  172.16.114.148   196.227.33.189     0
222882     1849       53  172.16.117.103     192.168.1.10     0
222883        0        0    192.168.1.90     192.168.1.10     1
222884    26689       25   194.7.248.153   172.16.114.168     0
222885     7618       80  172.16.112.207   204.71.177.179     0
222886     7808       80  172.16.113.105  136.149.142.178     0

[438165 rows x 5 columns]

In [30]:
truelist_1

       src_port dst_port          src_ip           dst_ip  type
0          1024       25   172.16.113.84   135.13.216.191     0
1            53       53    192.168.1.10    172.16.112.20     0
2            53       53    192.168.1.10    172.16.112.20     0
3          1025       25   172.16.113.84   197.182.91.233     0
4            53       53   172.16.112.20     192.168.1.20     0
5            53       53   172.16.112.20     192.168.1.20     0
6          1026       80  172.16.112.207    206.79.171.54     0
7          1027       80  172.16.112.207     207.77.90.16     0
8          1024       79  197.218.177.69   172.16.113.204     0
9          1028       80  172.16.115.234     209.1.224.15     0
10         1026       25  197.218.177.69   172.16.113.204     0
11         1027       21  197.218.177.69   172.16.114.148     0
12         1029       80  172.16.115.234     209.1.224.15     0
13         1048       80  172.16.115.234     209.1.224.15     0
14         1049       80  172.16.115.234     209.1.224.15     0
15         1051       80  172.16.115.234     209.1.224.15     0
16         1052       80  172.16.115.234     209.1.224.15     0
17         1104       80  172.16.115.234     209.1.224.15     0
18         1106       80  172.16.115.234     209.1.224.15     0
19         1107       80  172.16.115.234     209.1.224.15     0
20         1108       80  172.16.115.234     209.1.224.15     0
21         1109       80  172.16.115.234     209.1.224.15     0
22         1111       80  172.16.115.234     209.1.224.15     0
23         1112       80  172.16.115.234     209.1.224.15     0
24         1113       80  172.16.115.234     209.1.224.15     0
25         1115       80  172.16.115.234     209.1.224.15     0
26         1116       80  172.16.115.234   207.211.106.40     0
27           20     1028  172.16.114.148   197.218.177.69     0
28           20     1049  172.16.114.148   197.218.177.69     0
29         1060      161   194.27.251.21      192.168.1.1     0
...         ...      ...             ...              ...   ...
222858    33051       23         9.9.9.9    172.16.112.50     1
222859    33307       20         9.9.9.9    172.16.112.50     1
222860    33051       79         9.9.9.9    172.16.112.50     1
222861    33307       23         9.9.9.9    172.16.112.50     1
222862    33563       20         9.9.9.9    172.16.112.50     1
222863    33307       79         9.9.9.9    172.16.112.50     1
222864    33563       23         9.9.9.9    172.16.112.50     1
222865    33819       20         9.9.9.9    172.16.112.50     1
222866    33563       79         9.9.9.9    172.16.112.50     1
222867    33819       23         9.9.9.9    172.16.112.50     1
222868    34075       20         9.9.9.9    172.16.112.50     1
222869     1674      161   194.27.251.21      192.168.1.1     0
222870     7616       80  172.16.115.234  208.228.229.225     0
222871     1676      161   194.27.251.21      192.168.1.1     0
222872     1679      161   194.27.251.21      192.168.1.1     0
222873     7617       80  172.16.115.234     198.3.98.160     0
222874     7615       21  172.16.114.168   197.218.177.69     0
222875     1681      161   194.27.251.21      192.168.1.1     0
222876    26644       25   196.37.75.158   172.16.114.169     0
222877     1686      161   194.27.251.21      192.168.1.1     0
222878     1694      161   194.27.251.21      192.168.1.1     0
222879      161     1688     192.168.1.1    194.27.251.21     1
222880        0        0     192.168.1.1      192.168.1.5     1
222881       20    26652  172.16.114.148   196.227.33.189     0
222882     1849       53  172.16.117.103     192.168.1.10     0
222883        0        0    192.168.1.90     192.168.1.10     1
222884    26689       25   194.7.248.153   172.16.114.168     0
222885     7618       80  172.16.112.207   204.71.177.179     0
222886     7808       80  172.16.113.105  136.149.142.178     0
222887     1767      161   194.27.251.21      192.168.1.1     0

[450054 rows x 5 columns]

In [31]:
predictlist['type'].value_counts()

1    205010
0     17878
Name: type, dtype: int64

In [83]:
truelist_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227166 entries, 0 to 227165
Data columns (total 5 columns):
src_port    227166 non-null object
dst_port    227166 non-null object
src_ip      227166 non-null object
dst_ip      227166 non-null object
type        227166 non-null int64
dtypes: int64(1), object(4)
memory usage: 8.7+ MB

In [84]:
predictlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222888 entries, 0 to 222887
Data columns (total 5 columns):
src_port    222888 non-null int64
dst_port    222888 non-null int64
src_ip      222888 non-null object
dst_ip      222888 non-null object
type        222888 non-null int64
dtypes: int64(3), object(2)
memory usage: 8.5+ MB

In [114]:
a = truelist_1.head(5)

In [115]:
b = predictlist.head(5)

In [116]:
a

  src_port dst_port         src_ip          dst_ip  type
0     1024       25  172.16.113.84  135.13.216.191     0
1       53       53   192.168.1.10   172.16.112.20     0
2       53       53   192.168.1.10   172.16.112.20     0
3     1025       25  172.16.113.84  197.182.91.233     0
4       53       53  172.16.112.20    192.168.1.20     0

In [117]:
b

   src_port  dst_port          src_ip          dst_ip  type
0      1024        25   172.16.113.84  135.13.216.191     0
1      1025        25   172.16.113.84  197.182.91.233     0
2      1026        80  172.16.112.207   206.79.171.54     0
3      1027        80  172.16.112.207    207.77.90.16     0
4      1024        79  197.218.177.69  172.16.113.204     0

In [118]:
a_b = a.append(b)

In [119]:
a_b

  src_port dst_port          src_ip          dst_ip  type
0     1024       25   172.16.113.84  135.13.216.191     0
1       53       53    192.168.1.10   172.16.112.20     0
2       53       53    192.168.1.10   172.16.112.20     0
3     1025       25   172.16.113.84  197.182.91.233     0
4       53       53   172.16.112.20    192.168.1.20     0
0     1024       25   172.16.113.84  135.13.216.191     0
1     1025       25   172.16.113.84  197.182.91.233     0
2     1026       80  172.16.112.207   206.79.171.54     0
3     1027       80  172.16.112.207    207.77.90.16     0
4     1024       79  197.218.177.69  172.16.113.204     0

In [120]:
c = a_b.drop_duplicates(keep=False)

In [122]:
c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 0 to 4
Data columns (total 5 columns):
src_port    8 non-null object
dst_port    8 non-null object
src_ip      8 non-null object
dst_ip      8 non-null object
type        8 non-null int64
dtypes: int64(1), object(4)
memory usage: 384.0+ bytes

In [123]:
c

  src_port dst_port          src_ip          dst_ip  type
0     1024       25   172.16.113.84  135.13.216.191     0
3     1025       25   172.16.113.84  197.182.91.233     0
4       53       53   172.16.112.20    192.168.1.20     0
0     1024       25   172.16.113.84  135.13.216.191     0
1     1025       25   172.16.113.84  197.182.91.233     0
2     1026       80  172.16.112.207   206.79.171.54     0
3     1027       80  172.16.112.207    207.77.90.16     0
4     1024       79  197.218.177.69  172.16.113.204     0

In [133]:
type(c.iloc[0]['src_port'])

str

In [134]:
type(c.iloc[3]['src_port'])

int